Vagrant.configure("2") do |config|
  config.vm.box = "generic/alpine318"

  config.vm.define "pbiedermS" do |server|
    server.vm.hostname = "pbiedermS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.synced_folder "./confs", "/vagrant", type:"virtualbox"
    server.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = 2048
      vb.cpus = 1
      vb.name = "pbiedermS"
    end
    server.vm.provision "shell", path: "scripts/setup-server.sh"
  end
end
