Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"

  config.vm.define "kgebkiS" do |server|
    server.vm.hostname = "kgebkiS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end
    server.vm.provision "shell", path: "setup-server.sh"
  end

  config.vm.define "kgebkiSW" do |worker|
    worker.vm.hostname = "kgebkiSW"
    worker.vm.network "private_network", ip: "192.168.56.111"
    worker.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end
    worker.vm.provision "shell", path: "setup-worker.sh"
  end

  config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "/home/vagrant/.ssh/authorized_keys"
end