Vagrant.configure("2") do |config|
  config.vm.box = "generic/alpine318"

  config.vm.define "kgebskiS" do |server|
    server.vm.hostname = "kgebskiS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.synced_folder "./shared", "/vagrant", type:"virtualbox"
    server.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = 1024
      vb.cpus = 1
      vb.name = "kgebskiS"
    end
    server.vm.provision "shell", path: "setup-server.sh"
  end

  config.vm.define "kgebskiSW" do |worker|
    worker.vm.hostname = "kgebskiSW"
    worker.vm.network "private_network", ip: "192.168.56.111"
    worker.vm.synced_folder "./shared", "/vagrant", type:"virtualbox"
    worker.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = 1024
      vb.cpus = 1
      vb.name = "kgebskiSW"
    end
    worker.vm.provision "shell", path: "setup-worker.sh"
  end
end
