Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"

  config.vm.provider :libvirt do |libvirt|
    libvirt.memory = 1024
    libvirt.cpus = 1
  end


  config.vm.define "kgebkiS" do |server|
    server.vm.hostname = "kgebkiS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provision "shell", path: "setup-server.sh"
  end

  config.vm.define "kgebkiSW" do |worker|
    worker.vm.hostname = "kgebkiSW"
    worker.vm.network "private_network", ip: "192.168.56.111"
    worker.vm.provision "shell", path: "setup-worker.sh"
  end

  config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "/home/vagrant/.ssh/authorized_keys"
end